version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: 'float-mode'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5433:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    networks:
      - float-mode-network

  migration:
    image: andrewlimit/float-mode:${IMAGE_TAG}
    command: sh -c "poetry run alembic upgrade head"
    env_file:
      - .env.prod
    depends_on:
      - postgres
    networks:
      - float-mode-network

  app:
    image: andrewlimit/float-mode:${IMAGE_TAG}
    env_file:
      - .env.prod
    ports:
      - '8080:80'
    networks:
      - float-mode-network
    volumes:
      - './alembic/versions:/float-mode/alembic/versions'
      - './logs:/float-mode/logs'
    depends_on:
      - postgres
      - migration
    restart: always

  prometheus:
    image: docker.io/prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=5GB
    volumes:
      - './config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro'
      - './config/alert.rules.yaml:/etc/prometheus/alert.rules.yaml:ro'
      - 'prometheus-data:/prometheus'
    restart: always
    networks:
      - float-mode-network

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.28.1
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'
      - '--storage.path=/alertmanager'
    volumes:
      - './config/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml:ro'
      - './config/telegram.tmpl:/etc/alertmanager/telegram.tmpl:ro'
      - 'alertmanager-data:/alertmanager'
    networks:
      - float-mode-network

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    command: "--path.rootfs=/host"
    pid: host
    restart: always
    volumes:
      - /:/host:ro
    networks:
      - float-mode-network

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.17.1
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - postgres
    networks:
      - float-mode-network

  sql_exporter:
    image: burningalchemist/sql_exporter:0.18
    restart: always
    command:
      - --config.file=/etc/sql_exporter/config.yaml
    volumes:
      - './config/sql_exporter.yaml:/etc/sql_exporter/config.yaml:ro'
      - './config/pg_app.collector.yaml:/etc/sql_exporter/pg_app.collector.yaml:ro'
    env_file:
      - .env.prod
    depends_on:
      - postgres
    networks:
      - float-mode-network

volumes:
  prometheus-data:
    driver: local
  alertmanager-data:
    driver: local

networks:
  float-mode-network:
    driver: bridge
