services:
  migration:
    image: andrewlimit/float-mode:latest
    build: null
    volumes: []

  backend:
    image: andrewlimit/float-mode:latest
    build: null
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres:
    ports: []
    volumes:
      - "/var/lib/float-mode/pg:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    restart: always
    ports:
      - '80:80'
      - '443:443'
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  oauth2-proxy:
    command:
      - --provider=keycloak-oidc
      - --oidc-issuer-url=https://fly-potato.ru/sso/realms/${OAUTH2_REALMS}
      - --client-id=${OAUTH2_CLIENT_ID:-nginx-client}
      - --client-secret=${OAUTH2_CLIENT_SECRET}
      - --cookie-secret=${OAUTH2_COOKIE_SECRET}
      - --http-address=0.0.0.0:4180
      - --redirect-url=https://fly-potato.ru/oauth2/callback
      - --email-domain=*
      - --upstream=static://200
      - --pass-authorization-header=true
      - --set-authorization-header=true
      - --set-xauthrequest=true
      - --insecure-oidc-allow-unverified-email=true
      - --pass-access-token=true

  keycloak:
    environment:
      KC_PROXY: 'edge'
      KC_HOSTNAME: 'fly-potato.ru'
      KC_HTTP_RELATIVE_PATH: '/sso'
      KC_HTTP_ENABLED: 'true'