services:
  migration:
    image: andrewlimit/float-mode:latest
    build: null
    env_file:
      - .env.prod
    volumes: []

  backend:
    image: andrewlimit/float-mode:latest
    build: null
    env_file:
      - .env.prod
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres:
    ports: []
    volumes:
      - "./data/postgres16:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    restart: always
    ports:
      - '80:80'
      - '443:443'
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  oauth2-proxy:
    command:
      - --provider=keycloak-oidc
      - --oidc-issuer-url=https://fly-potato.ru/sso/realms/${OAUTH2_REALMS}
      - --client-id=${OAUTH2_CLIENT_ID:-nginx-client}
      - --client-secret=${OAUTH2_CLIENT_SECRET}
      - --cookie-secret=${OAUTH2_COOKIE_SECRET}
      - --cookie-expire=168h
      - --cookie-refresh=10m
      - --http-address=0.0.0.0:4180
      - --redirect-url=https://fly-potato.ru/oauth2/callback
      - --email-domain=*
      - --upstream=static://200
      - --pass-authorization-header=true
      - --set-authorization-header=true
      - --set-xauthrequest=true
      - --insecure-oidc-allow-unverified-email=true
      - --pass-access-token=true

  keycloak:
    environment:
      KC_PROXY: 'edge'
      KC_HOSTNAME: 'fly-potato.ru'
      KC_HTTP_RELATIVE_PATH: '/sso'
      KC_HTTP_ENABLED: 'true'

  grafana:
    environment:
      GF_SERVER_ROOT_URL: "https://fly-potato.ru/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SERVER_DOMAIN: "fly-potato.ru"
      GF_SERVER_ROUTER_LOGGING: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_PROXY_ENABLED: "false"
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD:-admin}